fix services.exim.environment.DISABLE_IPV6 error
[fix] WARNING: The SSLON variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.exim.environment.DISABLE_IPV6 contains true, which is an invalid type, it should be a string, number, or a null